# -*- coding: utf-8 -*-
"""OPTIMIZATION MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mute3MwoMp8xt59sJqS0FTXKi54iIxpU
"""

!pip install pulp

import pulp

model = pulp.LpProblem("Maximize_Production_Profit", pulp.LpMaximize)

x = pulp.LpVariable('Product_A', lowBound=0, cat='Integer')
y = pulp.LpVariable('Product_B', lowBound=0, cat='Integer')

model += 20*x + 30*y, "Total_Profit"

model += 1*x + 2*y <= 40, "Labor_Constraint"
model += 1*x + 1*y <= 30, "Material_Constraint"

print("Solving the optimization problem...")
model.solve()

status = pulp.LpStatus[model.status]
print(f"Solution Status: {status}")

if status == 'Optimal':
    # Get the optimal values for x and y
    optimal_a = pulp.value(x)
    optimal_b = pulp.value(y)

    # Get the maximum profit
    max_profit = pulp.value(model.objective)

    print("\n--- Optimal Solution ---")
    print(f"Units of Product A to produce: {optimal_a}")
    print(f"Units of Product B to produce: {optimal_b}")
    print(f"Maximum Daily Profit: ${max_profit:,.2f}")

    # Check resource usage (Insights)
    total_labor = pulp.value(1*x + 2*y)
    total_material = pulp.value(1*x + 1*y)

    print("\n--- Resource Usage (Insights) ---")
    print(f"Labor Used: {total_labor} of 40 hours available.")
    print(f"Material Used: {total_material} of 30 kg available.")

    # Provide final insight
    print("\nInsight:")
    print("To maximize profit, the factory should produce 20 units of Product A and 10 units of Product B.")
    print("This solution will use all 40 hours of labor and all 30 kg of material, meaning resources are perfectly utilized.")

else:
    print("No optimal solution found. Check the constraints.")